name: dev_vnf
channels:
  - conda-forge
dependencies:
  - aiohttp
  - bs4
  - ca-certificates
  - certifi
  - ipympl
  - jupyter
  - matplotlib
  - openpyxl
  - openssl
  - pandas
  - python=3.12
  - requests
  - xarray
 