name: dev_vnf
channels:
  - conda-forge
dependencies:
  - aiohttp
  - bs4
  - ipympl
  - ipywidgets
  - matplotlib
  - openpyxl
  - openssl
  - pandas
  - python=3.12
  - requests
  - seaborn
  - xarray
